// Generated by https://quicktype.io

export interface IDatos {
  codigoProducto ?: number;
  nombre:         string | unknown | null;
  precio:         number | unknown | null;
  tipo :           number | unknown | null;
  foto :         string | unknown | null;
}
